// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/ether8021x.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EapType int32

const (
	EapType_EAP_UNKNOWN EapType = 0
	EapType_EAP_TLS     EapType = 1
	EapType_EAP_PEAP    EapType = 2
	EapType_EAP_TTLS    EapType = 3
	EapType_EAP_FAST    EapType = 4
)

// Enum value maps for EapType.
var (
	EapType_name = map[int32]string{
		0: "EAP_UNKNOWN",
		1: "EAP_TLS",
		2: "EAP_PEAP",
		3: "EAP_TTLS",
		4: "EAP_FAST",
	}
	EapType_value = map[string]int32{
		"EAP_UNKNOWN": 0,
		"EAP_TLS":     1,
		"EAP_PEAP":    2,
		"EAP_TTLS":    3,
		"EAP_FAST":    4,
	}
)

func (x EapType) Enum() *EapType {
	p := new(EapType)
	*p = x
	return p
}

func (x EapType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EapType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_ether8021x_proto_enumTypes[0].Descriptor()
}

func (EapType) Type() protoreflect.EnumType {
	return &file_proto_ether8021x_proto_enumTypes[0]
}

func (x EapType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EapType.Descriptor instead.
func (EapType) EnumDescriptor() ([]byte, []int) {
	return file_proto_ether8021x_proto_rawDescGZIP(), []int{0}
}

type Dot1XConfigRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Interface          string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	EapType            EapType                `protobuf:"varint,2,opt,name=eap_type,json=eapType,proto3,enum=ether8021x.EapType" json:"eap_type,omitempty"`
	Identity           string                 `protobuf:"bytes,3,opt,name=identity,proto3" json:"identity,omitempty"`
	Password           string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Phase2Auth         string                 `protobuf:"bytes,5,opt,name=phase2_auth,json=phase2Auth,proto3" json:"phase2_auth,omitempty"`
	CaCert             []byte                 `protobuf:"bytes,6,opt,name=ca_cert,json=caCert,proto3" json:"ca_cert,omitempty"`
	ClientCert         []byte                 `protobuf:"bytes,7,opt,name=client_cert,json=clientCert,proto3" json:"client_cert,omitempty"`
	PrivateKey         []byte                 `protobuf:"bytes,8,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	PrivateKeyPassword string                 `protobuf:"bytes,9,opt,name=private_key_password,json=privateKeyPassword,proto3" json:"private_key_password,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Dot1XConfigRequest) Reset() {
	*x = Dot1XConfigRequest{}
	mi := &file_proto_ether8021x_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dot1XConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dot1XConfigRequest) ProtoMessage() {}

func (x *Dot1XConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ether8021x_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dot1XConfigRequest.ProtoReflect.Descriptor instead.
func (*Dot1XConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_ether8021x_proto_rawDescGZIP(), []int{0}
}

func (x *Dot1XConfigRequest) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *Dot1XConfigRequest) GetEapType() EapType {
	if x != nil {
		return x.EapType
	}
	return EapType_EAP_UNKNOWN
}

func (x *Dot1XConfigRequest) GetIdentity() string {
	if x != nil {
		return x.Identity
	}
	return ""
}

func (x *Dot1XConfigRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *Dot1XConfigRequest) GetPhase2Auth() string {
	if x != nil {
		return x.Phase2Auth
	}
	return ""
}

func (x *Dot1XConfigRequest) GetCaCert() []byte {
	if x != nil {
		return x.CaCert
	}
	return nil
}

func (x *Dot1XConfigRequest) GetClientCert() []byte {
	if x != nil {
		return x.ClientCert
	}
	return nil
}

func (x *Dot1XConfigRequest) GetPrivateKey() []byte {
	if x != nil {
		return x.PrivateKey
	}
	return nil
}

func (x *Dot1XConfigRequest) GetPrivateKeyPassword() string {
	if x != nil {
		return x.PrivateKeyPassword
	}
	return ""
}

type Dot1XConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dot1XConfigResponse) Reset() {
	*x = Dot1XConfigResponse{}
	mi := &file_proto_ether8021x_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dot1XConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dot1XConfigResponse) ProtoMessage() {}

func (x *Dot1XConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ether8021x_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dot1XConfigResponse.ProtoReflect.Descriptor instead.
func (*Dot1XConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_ether8021x_proto_rawDescGZIP(), []int{1}
}

func (x *Dot1XConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *Dot1XConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InterfaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceRequest) Reset() {
	*x = InterfaceRequest{}
	mi := &file_proto_ether8021x_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceRequest) ProtoMessage() {}

func (x *InterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ether8021x_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceRequest.ProtoReflect.Descriptor instead.
func (*InterfaceRequest) Descriptor() ([]byte, []int) {
	return file_proto_ether8021x_proto_rawDescGZIP(), []int{2}
}

func (x *InterfaceRequest) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

type InterfaceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     string                 `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	EapState      string                 `protobuf:"bytes,3,opt,name=eap_state,json=eapState,proto3" json:"eap_state,omitempty"`
	LastEvent     string                 `protobuf:"bytes,4,opt,name=last_event,json=lastEvent,proto3" json:"last_event,omitempty"`
	IpAddress     string                 `protobuf:"bytes,5,opt,name=ip_address,json=ipAddress,proto3" json:"ip_address,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceStatus) Reset() {
	*x = InterfaceStatus{}
	mi := &file_proto_ether8021x_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceStatus) ProtoMessage() {}

func (x *InterfaceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ether8021x_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceStatus.ProtoReflect.Descriptor instead.
func (*InterfaceStatus) Descriptor() ([]byte, []int) {
	return file_proto_ether8021x_proto_rawDescGZIP(), []int{3}
}

func (x *InterfaceStatus) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *InterfaceStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InterfaceStatus) GetEapState() string {
	if x != nil {
		return x.EapState
	}
	return ""
}

func (x *InterfaceStatus) GetLastEvent() string {
	if x != nil {
		return x.LastEvent
	}
	return ""
}

func (x *InterfaceStatus) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *InterfaceStatus) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type DisconnectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectResponse) Reset() {
	*x = DisconnectResponse{}
	mi := &file_proto_ether8021x_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectResponse) ProtoMessage() {}

func (x *DisconnectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ether8021x_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectResponse.ProtoReflect.Descriptor instead.
func (*DisconnectResponse) Descriptor() ([]byte, []int) {
	return file_proto_ether8021x_proto_rawDescGZIP(), []int{4}
}

func (x *DisconnectResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DisconnectResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_ether8021x_proto protoreflect.FileDescriptor

const file_proto_ether8021x_proto_rawDesc = "" +
	"\n" +
	"\x16proto/ether8021x.proto\x12\n" +
	"ether8021x\"\xc8\x02\n" +
	"\x12Dot1xConfigRequest\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12.\n" +
	"\beap_type\x18\x02 \x01(\x0e2\x13.ether8021x.EapTypeR\aeapType\x12\x1a\n" +
	"\bidentity\x18\x03 \x01(\tR\bidentity\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1f\n" +
	"\vphase2_auth\x18\x05 \x01(\tR\n" +
	"phase2Auth\x12\x17\n" +
	"\aca_cert\x18\x06 \x01(\fR\x06caCert\x12\x1f\n" +
	"\vclient_cert\x18\a \x01(\fR\n" +
	"clientCert\x12\x1f\n" +
	"\vprivate_key\x18\b \x01(\fR\n" +
	"privateKey\x120\n" +
	"\x14private_key_password\x18\t \x01(\tR\x12privateKeyPassword\"I\n" +
	"\x13Dot1xConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"0\n" +
	"\x10InterfaceRequest\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\"\xc0\x01\n" +
	"\x0fInterfaceStatus\x12\x1c\n" +
	"\tinterface\x18\x01 \x01(\tR\tinterface\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1b\n" +
	"\teap_state\x18\x03 \x01(\tR\beapState\x12\x1d\n" +
	"\n" +
	"last_event\x18\x04 \x01(\tR\tlastEvent\x12\x1d\n" +
	"\n" +
	"ip_address\x18\x05 \x01(\tR\tipAddress\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\"H\n" +
	"\x12DisconnectResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*Q\n" +
	"\aEapType\x12\x0f\n" +
	"\vEAP_UNKNOWN\x10\x00\x12\v\n" +
	"\aEAP_TLS\x10\x01\x12\f\n" +
	"\bEAP_PEAP\x10\x02\x12\f\n" +
	"\bEAP_TTLS\x10\x03\x12\f\n" +
	"\bEAP_FAST\x10\x042\xc6\x02\n" +
	"\fDot1xManager\x12U\n" +
	"\x12ConfigureInterface\x12\x1e.ether8021x.Dot1xConfigRequest\x1a\x1f.ether8021x.Dot1xConfigResponse\x12F\n" +
	"\tGetStatus\x12\x1c.ether8021x.InterfaceRequest\x1a\x1b.ether8021x.InterfaceStatus\x12K\n" +
	"\fStreamStatus\x12\x1c.ether8021x.InterfaceRequest\x1a\x1b.ether8021x.InterfaceStatus0\x01\x12J\n" +
	"\n" +
	"Disconnect\x12\x1c.ether8021x.InterfaceRequest\x1a\x1e.ether8021x.DisconnectResponseB(Z&github.com/gavmckee80/dot1x-grpc/protob\x06proto3"

var (
	file_proto_ether8021x_proto_rawDescOnce sync.Once
	file_proto_ether8021x_proto_rawDescData []byte
)

func file_proto_ether8021x_proto_rawDescGZIP() []byte {
	file_proto_ether8021x_proto_rawDescOnce.Do(func() {
		file_proto_ether8021x_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ether8021x_proto_rawDesc), len(file_proto_ether8021x_proto_rawDesc)))
	})
	return file_proto_ether8021x_proto_rawDescData
}

var file_proto_ether8021x_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_ether8021x_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_ether8021x_proto_goTypes = []any{
	(EapType)(0),                // 0: ether8021x.EapType
	(*Dot1XConfigRequest)(nil),  // 1: ether8021x.Dot1xConfigRequest
	(*Dot1XConfigResponse)(nil), // 2: ether8021x.Dot1xConfigResponse
	(*InterfaceRequest)(nil),    // 3: ether8021x.InterfaceRequest
	(*InterfaceStatus)(nil),     // 4: ether8021x.InterfaceStatus
	(*DisconnectResponse)(nil),  // 5: ether8021x.DisconnectResponse
}
var file_proto_ether8021x_proto_depIdxs = []int32{
	0, // 0: ether8021x.Dot1xConfigRequest.eap_type:type_name -> ether8021x.EapType
	1, // 1: ether8021x.Dot1xManager.ConfigureInterface:input_type -> ether8021x.Dot1xConfigRequest
	3, // 2: ether8021x.Dot1xManager.GetStatus:input_type -> ether8021x.InterfaceRequest
	3, // 3: ether8021x.Dot1xManager.StreamStatus:input_type -> ether8021x.InterfaceRequest
	3, // 4: ether8021x.Dot1xManager.Disconnect:input_type -> ether8021x.InterfaceRequest
	2, // 5: ether8021x.Dot1xManager.ConfigureInterface:output_type -> ether8021x.Dot1xConfigResponse
	4, // 6: ether8021x.Dot1xManager.GetStatus:output_type -> ether8021x.InterfaceStatus
	4, // 7: ether8021x.Dot1xManager.StreamStatus:output_type -> ether8021x.InterfaceStatus
	5, // 8: ether8021x.Dot1xManager.Disconnect:output_type -> ether8021x.DisconnectResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_ether8021x_proto_init() }
func file_proto_ether8021x_proto_init() {
	if File_proto_ether8021x_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ether8021x_proto_rawDesc), len(file_proto_ether8021x_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ether8021x_proto_goTypes,
		DependencyIndexes: file_proto_ether8021x_proto_depIdxs,
		EnumInfos:         file_proto_ether8021x_proto_enumTypes,
		MessageInfos:      file_proto_ether8021x_proto_msgTypes,
	}.Build()
	File_proto_ether8021x_proto = out.File
	file_proto_ether8021x_proto_goTypes = nil
	file_proto_ether8021x_proto_depIdxs = nil
}
